force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Nombre de Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha_2_code__c.field-meta.xml
<CustomField>
    <fullName>alpha_2_code__c</fullName>
    <label>alpha 2 code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryAPI_Test.cls
@isTest
public class CountryAPI_Test {

    @isTest
    static void upsertCountries_test() {
        
        Test.setMock(HttpCalloutMock.class, new CountryAPIMockCallout());
        
        country__c pais =new country__C();
        pais.name='España';
        pais.alpha_2_code__c='ES';
        insert pais;
        
        test.startTest();

        CountryAPIUpdate.upsertCountries();
        
        List<Country__c> countries = [SELECT id,name,alpha_2_code__c FROM Country__c];
        System.assertEquals(2, countries.size());
        for(country__c con :countries){
            if(con.name=='España'){
                System.assertEquals('ES', con.alpha_2_code__c);
            }else{
                System.assertEquals('PT', con.alpha_2_code__c);
            }
        }
        
        test.stopTest();
    }
}